### ISSUE TITLE
Gemspec

### ISSUE THREAD

**Issue by fidelisrafael** [oswaldoferreira/action_bouncer#1]
Fala @oswaldoferreira, to tentando rodar pra enviar um pequeno PR, porém quando executo `bundle install`, recebo o erro:

```
[!] There was an error parsing `Gemfile`: There are no gemspecs at /(...)/action_bouncer.. Bundler cannot continue.

 #  from /(...)/action_bouncer/Gemfile:3
 #  -------------------------------------------
 #
 >  gemspec
 #
 #  -------------------------------------------
```

Alterei o `Gemfile` e adicionei:

```
gem 'rails'
gem 'sqlite3'
gem 'rspec-rails'
```

E consegui rodar normalmente, porém é uma medida paliativa por hora!
Alguma sugestão?

Há braços!

**Comment by oswaldoferreira** [comment]
Olá @fidelisrafael, adicionei o `.gemspec` ao projeto (https://github.com/oswaldoferreira/action_bouncer/commit/b4d48debded0a434934acb2affc67c31e0a04a50), você não terá mais problemas com o setup.

**Comment by oswaldoferreira** [comment]
@fidelisrafael Vou fechar o issue, se houver mais algum problema relacionado pode reabrir.

**Comment by fidelisrafael** [comment]
@oswaldoferreira Do caraleo! Valeu! :clap:
